name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ▼▼▼▼▼ 修正後のデバッグステップ 1 ▼▼▼▼▼
      - name: 'Debug: Display script.js content BEFORE replacement'
        run: |
          echo "--- Content of docs/script.js BEFORE replacement ---"
          cat docs/script.js | grep "const apiKey"
          echo "----------------------------------------------------"

      - name: Replace API Key
        run: sed -i "s|GEMINI_API_KEY_PLACEHOLDER|${{ secrets.GEMINI_API_KEY }}|g" docs/index.html docs/script.js
        
      # ▼▼▼▼▼ 修正後のデバッグステップ 2 ▼▼▼▼▼
      - name: 'Debug: Display script.js content AFTER replacement'
        run: |
          echo "--- Content of docs/script.js AFTER replacement ---"
          cat docs/script.js | grep "const apiKey"
          echo "---------------------------------------------------"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
